const phones = [
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Apple",
    model: "iPhone 15",
    storage: "128GB",
    color: "Black",
    price: 1200,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Samsung",
    model: "Galaxy S23",
    storage: "256GB",
    color: "White",
    price: 1100,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Xiaomi",
    model: "Mi 13",
    storage: "128GB",
    color: "Blue",
    price: 900,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Google",
    model: "Pixel 7",
    storage: "256GB",
    color: "Green",
    price: 1000,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "OnePlus",
    model: "11 Pro",
    storage: "512GB",
    color: "Red",
    price: 1050,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Sony",
    model: "Xperia 1 V",
    storage: "256GB",
    color: "Purple",
    price: 1150,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Huawei",
    model: "P60 Pro",
    storage: "512GB",
    color: "Silver",
    price: 980,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Realme",
    model: "GT 3",
    storage: "128GB",
    color: "Orange",
    price: 850,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Motorola",
    model: "Edge 40",
    storage: "256GB",
    color: "Gray",
    price: 870,
  },
  {
    url:"https://i.ytimg.com/vi/UglLxXAxkcU/maxresdefault.jpg",
    brand: "Asus",
    model: "ROG Phone 7",
    storage: "1TB",
    color: "Black",
    price: 1300,
  },
];

export default phones;
